// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/credentials_usecase.go
//
// Generated by this command:
//
//	mockgen -package mocks -destination ./internal/usecase/mocks/mock_credentials_usecase.go -source ./internal/usecase/credentials_usecase.go
//

// Package mocks is a generated GoMock package.
package mocks
